source 'https://rubygems.org'
ruby '2.1.0'
gem 'log4ever'
gem 'parallel_runner'
gem 'mechanize'
gem 'httpclient'
gem 'clockwork'
gem 'twitter', '>=4.4.4'
gem 'tweetstream'
gem 'sys-proctable'
gem 'json'
